{-# OPTIONS_GHC -w #-}
{-# LANGUAGE GADTs, TypeSynonymInstances, FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Frontend.Parser.PrintLatte where

-- pretty-printer generated by the BNF converter

import Frontend.Parser.AbsLatte
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print TopDef where
  prt i e = case e of
    FnTopDef fndef -> prPrec i 0 (concatD [prt 0 fndef])
    ClsTopDef clsdef -> prPrec i 0 (concatD [prt 0 clsdef])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print MemberDef where
  prt i e = case e of
    MetDef fndef -> prPrec i 0 (concatD [prt 0 fndef])
    FieldDef type_ fditems -> prPrec i 0 (concatD [prt 0 type_, prt 0 fditems, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print FdItem where
  prt i e = case e of
    FdNoInit id -> prPrec i 0 (concatD [prt 0 id])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Arg where
  prt i e = case e of
    Arg type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print FnDef where
  prt i e = case e of
    FnDef type_ id args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print ClsDef where
  prt i e = case e of
    ClsDef id memberdefs -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id, doc (showString "{"), prt 0 memberdefs, doc (showString "}")])
    ClsDefEx id1 id2 memberdefs -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id1, doc (showString "extends"), prt 0 id2, doc (showString "{"), prt 0 memberdefs, doc (showString "}")])

instance Print Block where
  prt i e = case e of
    Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print Stmt where
  prt i e = case e of
    Empty -> prPrec i 0 (concatD [doc (showString ";")])
    BStmt block -> prPrec i 0 (concatD [prt 0 block])
    Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    Ass lval expr -> prPrec i 0 (concatD [prt 0 lval, doc (showString "="), prt 0 expr, doc (showString ";")])
    Incr lval -> prPrec i 0 (concatD [prt 0 lval, doc (showString "++"), doc (showString ";")])
    Decr lval -> prPrec i 0 (concatD [prt 0 lval, doc (showString "--"), doc (showString ";")])
    Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    For type_ id expr stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 type_, prt 0 id, doc (showString ":"), prt 0 expr, doc (showString ")"), prt 0 stmt])
    SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Item where
  prt i e = case e of
    NoInit id -> prPrec i 0 (concatD [prt 0 id])
    Init id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Type where
  prt i e = case e of
    IntT -> prPrec i 0 (concatD [doc (showString "int")])
    StringT -> prPrec i 0 (concatD [doc (showString "string")])
    BooleanT -> prPrec i 0 (concatD [doc (showString "boolean")])
    VoidT -> prPrec i 0 (concatD [doc (showString "void")])
    ClassT id -> prPrec i 0 (concatD [prt 0 id])
    ArrayT type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])
    FunT type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Expr where
  prt i e = case e of
    ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    ELitNull type_ -> prPrec i 6 (concatD [doc (showString "("), prt 0 type_, doc (showString ")null")])
    EString str -> prPrec i 6 (concatD [prt 0 str])
    EApp id exprs -> prPrec i 6 (concatD [prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    ClsApply expr id exprs -> prPrec i 6 (concatD [prt 6 expr, doc (showString "."), prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    TClsApply type_ expr id exprs -> prPrec i 6 (concatD [doc (showString "("), prt 0 type_, doc (showString ")"), prt 6 expr, doc (showString "."), prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    ELVal lval -> prPrec i 6 (concatD [prt 0 lval])
    ArrAlloc type_ expr -> prPrec i 5 (concatD [doc (showString "new"), prt 0 type_, doc (showString "["), prt 0 expr, doc (showString "]")])
    ClsAlloc id -> prPrec i 5 (concatD [doc (showString "new"), prt 0 id])
    Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    EMul expr1 op expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 2 op, prt 5 expr2])
    EAdd expr1 op expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 1 op, prt 4 expr2])
    ERel expr1 op expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 3 op, prt 3 expr2])
    EAnd expr1 op expr2 -> prPrec i 1 (concatD [prt 2 expr1, prt 4 op, prt 1 expr2])
    EOr expr1 op expr2 -> prPrec i 0 (concatD [prt 1 expr1, prt 5 op, prt 0 expr2])
    EBinOp expr1 op expr2 -> prPrec i 0 (concatD [prt 0 expr1, prt 0 op, prt 0 expr2])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print LVal where
  prt i e = case e of
    LVar id -> prPrec i 0 (concatD [prt 0 id])
    LArrAcc expr1 expr2 -> prPrec i 0 (concatD [prt 6 expr1, doc (showString "["), prt 0 expr2, doc (showString "]")])
    LClsAcc expr id -> prPrec i 0 (concatD [prt 6 expr, doc (showString "."), prt 0 id])
    LTClsAcc type_ expr id -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_, doc (showString ")"), prt 6 expr, doc (showString "."), prt 0 id])

instance Print Op where
  prt i e = case e of
    Plus -> prPrec i 1 (concatD [doc (showString "+")])
    Minus -> prPrec i 1 (concatD [doc (showString "-")])
    Times -> prPrec i 2 (concatD [doc (showString "*")])
    Div -> prPrec i 2 (concatD [doc (showString "/")])
    Mod -> prPrec i 2 (concatD [doc (showString "%")])
    LTH -> prPrec i 3 (concatD [doc (showString "<")])
    LE -> prPrec i 3 (concatD [doc (showString "<=")])
    GTH -> prPrec i 3 (concatD [doc (showString ">")])
    GE -> prPrec i 3 (concatD [doc (showString ">=")])
    EQU -> prPrec i 3 (concatD [doc (showString "==")])
    NE -> prPrec i 3 (concatD [doc (showString "!=")])
    AND -> prPrec i 4 (concatD [doc (showString "&&")])
    OR -> prPrec i 5 (concatD [doc (showString "||")])
    EQU_Int -> prPrec i 0 (concatD [doc (showString "==")])
    EQU_Str -> prPrec i 0 (concatD [doc (showString "==")])
    EQU_Arr -> prPrec i 0 (concatD [doc (showString "==")])
    EQU_Ref -> prPrec i 0 (concatD [doc (showString "==")])
    EQU_Bool -> prPrec i 0 (concatD [doc (showString "==")])
    NE_Int -> prPrec i 0 (concatD [doc (showString "!=")])
    NE_Str -> prPrec i 0 (concatD [doc (showString "!=")])
    NE_Arr -> prPrec i 0 (concatD [doc (showString "!=")])
    NE_Ref -> prPrec i 0 (concatD [doc (showString "!=")])
    NE_Bool -> prPrec i 0 (concatD [doc (showString "!=")])
    Plus_Int -> prPrec i 0 (concatD [doc (showString "+")])
    Plus_Str -> prPrec i 0 (concatD [doc (showString "+")])


